[default]

[conf]
# DB connectivity, the user must be able to read/write every PG object there.
# DB_PASSWORD must match POSTGRES_PASSWORD / DB_PASSWORD in .env
DB_USER = postgres
DB_PASSWORD = 0a5357c66d6a300236df955169e8349e
DB_HOST = pgdb
DB_PORT = 5432
DB_DATABASE = ecotaxa
# Read-only user, to same or other DB, the user must be able to read tables there.
# No separate read replica here, so just point back at the same DB/user.
RO_DB_USER = postgres
RO_DB_PASSWORD = 0a5357c66d6a300236df955169e8349e
RO_DB_HOST = pgdb
RO_DB_PORT = 5432
RO_DB_DATABASE = ecotaxa

# Application manager is named in some pages (e.g. Import help) and is available at /api/constants
APPMANAGER_EMAIL = murray.tylar@gmail.com
APPMANAGER_NAME = EcoTaxa Admin

# During import, images with any dimension larger than below will be stored reduced
THUMBSIZELIMIT = 400

# Where all images are stored. r/w by the back-end.
VAULT_DIR = /vault
# One subdirectory here per job. r/w by the back-end.
JOBS_DIR = /temp_jobs
# The directory where files can be read by everyone. ro by the back-end.
SERVERLOADAREA = /file_srv
# Sub-directory of previous (or not), for exports. r/w by the back-end.
FTPEXPORTAREA = /ftp_area
# CNN models. ro by the back-end.
MODELSAREA = /models

# Communication settings with the taxonomy server
TAXOSERVER_URL = https://ecotaxoserver.obs-vlfr.fr
TAXOSERVER_INSTANCE_ID = 9
TAXOSERVER_SHARED_SECRET = ZiAgKGDHiQ4WAj6Gi1RN41WHrMkPut8B3AzgXqLWZ

# If you want to enable reCaptcha for user creation
# Note: Below values are for testing,
# see https://developers.google.com/recaptcha/docs/faq#id-like-to-run-automated-tests-with-recaptcha.-what-should-i-do
#RECAPTCHAID = 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
#RECAPTCHASECRET = 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe

# Password encryption parameters
# The same value must be present on front-end config.cfg (SECRET_KEY)
SECRET_KEY = 1bfd6212b728b7f98c7ce989e79e9c92cb49893e
SECURITY_PASSWORD_HASH = sha512_crypt
SECURITY_PASSWORD_SALT = de07f6319b1b3827
# key can be shared with the front
MAILSERVICE_SECRET_KEY = cfda1bf23461c8a772c18285a674be354d78e66d
MAILSERVICE_SALT = 3655c31baa955d10
# email address used in account management : mandatory - 0 email - 1 pwd - 2 - dns - [...3 smtp port - 4 imap port]
SENDER_ACCOUNT = noreply@senderaccount.mail,passwdaccount,ssl0.ovh.net,465,993
#EcoTaxa instance id
INSTANCE_ID = EcoTaxa.local
# email verification request before user creation
USER_EMAIL_VERIFICATION = off
#if "on" - account validation is needed for registration and account major data modification
ACCOUNT_VALIDATION = off
# account mail templates
DIR_MAIL_TEMPLATES = /account_validation_mails
# comment next line if no ticket software is used or account validation if off - or add the value of the FROM search criteria in imap mailbox
#ADD_TICKET = sismer@ifremer.fr
#FRONT URL
SERVERURL = http://seabreeze.marine.usf.edu:8088

#user directory root
USERSFILESAREA = /eco_users_files
# max upload file size in bytes
MAX_UPLOAD_SIZE = 681574400
# number of days before deleting my files directories
TIMETOLIVE = 60
# If you want to run all_in_one install set to "on"
ALL_IN_ONE = on
